name: nextgen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_search_bar: ^2.5.0
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0  
  carousel_slider: ^4.0.0
  line_awesome_flutter: ^2.0.0
  flutter_screenutil: ^5.9.0
  animated_theme_switcher: ^2.0.10
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  firebase_core: ^2.24.2
  share_plus: ^7.2.1
  url_launcher: ^6.0.9
  firebase_dynamic_links: ^5.4.8
  flutter_pdfview: ^1.0.2
  nfc_manager: ^3.3.0
  http: ^1.2.0
  convert: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpeg
    - assets/images/img5.jpeg
    - assets/images/img6.jpeg
    - assets/images/classic.jpg
    - assets/images/fantasy.jpg
    - assets/images/horror.jpg
    - assets/images/comic.jpg
    - assets/images/user2.jpeg
    - assets/images/user3.jpeg
    - assets/images/user4.png
    - assets/books/book1.pdf
    
